name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rsync files to server
        uses: tempersama/rsync-copy@2.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          source: './'
          destination: '/home/adideveloper/domains/start-laravel-react-ts/main-app'
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          args: >
            -avz
            --delete
            --exclude='.git'
            --exclude='.github'
            --exclude='.gitignore'
            --exclude='*.git'
            --exclude='public/index.php'

      - name: Rsync Public Laravel
        uses: tempersama/rsync-copy@2.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          source: ./public/
          destination: /home/adideveloper/domains/start-laravel-react-ts/public_html
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          args: >
            -avz
            --delete
